### ISSUE TITLE
Wrong Ports on Healthcheck Target Config Parse?

### ISSUE THREAD

**Issue by rpattcorner** [cloudamatic/mu#63]
Branch six_pack_albs

The symptom is that with an ALB (classic: false) with a nonstandard (8080 not 80) port and a BOK like this:

```
  healthcheck:
   target: "HTTP:8080/"
   timeout: 5
   interval: 30
   unhealthy-threshold: 2
   healthy-threshold: 2
```
I see two issues:
* The three status codes don't make it thru to the ALB, just the 200 code
* Spurious error indicating an incorrect string (not serious but probably indicative of the problem
```
Apr 10 13:50:55 - config - Classic-style ELB health check target HTTP:8080/index.html invalid for ALB targetgroup jira-lbhttp80 (HTTP:8080). Creating approximate configuration:
        {
  "details": {
    "target": "HTTP:8080/",
    "timeout": 5,
    "interval": 30,
    "unhealthy_threshold": 2,
    "healthy_threshold": 2,
    "httpcode": "200,301,302"
  }
}
```

In digging into config.rb where we parse the healthcheck target I see (note my log statements)
```
if lb["healthcheck"]
                hc_target = lb['healthcheck']['target'].match(/^([^:]+):(\d+)(.*)/)
                MU.log "====== #{hc_target} #{hc_target[1]} #{hc_target[2]}
                ===="
                MU.log l["lb_protocol"]
                MU.log l["lb_port"].to_s
                if hc_target[1] == l["lb_protocol"] and
                   hc_target[2] == l["lb_port"].to_s
                  tg["healthcheck"] = lb['healthcheck'].dup
                else
                  tg["healthcheck"] = lb['healthcheck'].dup
                  tg['healthcheck']['target'] = "#{l["instance_protocol"]}:#{l["instance_port"]}/"
                  tg['healthcheck']["httpcode"] = "200,301,302"
                  MU.log "Classic-style ELB health check target #{lb['healthcheck']['target']} invalid for ALB targetgroup #{tgname} (#{l["instance_protocol"]}:#{l["instance_port"]}). Creating approximate configuration:", MU::WARN, details: tg['healthcheck']
                end
              end

```

Shouldn't we be checking against instance_protocol and instance_port instead of lb_protocol and lb_port?  In any event, the code is looking for a match to port 80 where I've specified 8080

**Comment by jstange** [comment]
That's not actually what the logic of that `if` statement is for. It's saying that if the outside and inside match exactly, it's ok to just duplicate the classic-style health check configuration (because then we know we have a sane combination of parameters for ALBs). Otherwise it does something slightly more complicated. 

There's nothing wrong with that logic, but it is slightly circuitous. I'm replacing it with this, which is more to-the-point: 

```
                proto = !["HTTP", "HTTPS"].include?(hc_target[1]) ? hc_target[1] : l["instance_protocol"]
                tg['healthcheck']['target'] = "#{proto}:#{l["instance_port"]}#{hc_target[3]}"
```

I do see AWS ignoring the status codes we pass in. I'll see if I can fix that.

The warning's not spurious. Application Load Balancers move the health check into the target groups. They're no longer an artifact of the LBs themselves. The pedantically correct BoK would declare the target groups and stick health checks in there. We're covering a degenerate case here so we don't have to do that on all the old stuff, and that's the message telling you that we're making stuff up.

**Comment by jstange** [comment]
Committed improvements.

**Comment by rpattcorner** [comment]
Looks good!
