### ISSUE TITLE
sketchy python cookbook

### ISSUE THREAD

**Issue by jstange** [cloudamatic/mu#79]
We have an old community cookbook that someone grafted into our repo ages ago: https://github.com/cloudamatic/mu/tree/master/cookbooks/python

It's in the repo because it's been officially deprecated and replaced by `poise-python`, but something we have supposedly needs this one. I'm not entirely sure what its purpose in life is. It may be a dependency for some other archaic cookbook; it may just be something someone used in a demo once.

Github is now helpfully perusing Gemfiles and telling you have it you have dependencies with known security vulnerabilities, and would you look at that it has complaints about this one:

https://github.com/cloudamatic/mu/network/dependencies#978256

We should figure out why we carry this cookbook in the first place, then either get rid of it or haul it boldly into the present.

**Comment by agill17** [comment]
Python cookbook is listed as dependencies in few cookbooks metadata file
   - mu-activedirectory , mu-tools
However **none** of the python recipes and custom resources are **included** or being used in mu-activedirectory cookbook -- So we can remove the python dependency from there.

-----------------------------------------------------------------------------------

In **mu-tools::ebs_rolling_snapshots**, python's default recipe is **included**.
 --- POSSIBLE_FIX: Instead try to use poise_python default recipe
We are also utilizing a custom resource from python cookbook "python_pip" to upgrade some packages
 --- POSSIBLE_FIX: Instead try to use poise_python resource and actions to upgrade whatever it is attempting to upgrade
 
- Is mu-tools::ebs_rolling_snapshots part of any roles run_list? No

-----------------------------------------------------------------------------------


We have **included** python default **recipe** inside one of the mu site_cookbooks (site_cookbooks/demo/recipes/flask.rb) -- for demo purposes I assume. 
 --- POSSIBLE_FIX: Update this to use poise python.

-----------------------------------------------------------------------------------

Python cookbook is also included in Berksfile as a local cookbook path in the root directory of mu repository.
Now getting rid of it completely might result into Berksfile dependency issues unless we point to poise-python (which will not be in a local path, so just update the metadata) only if other cookbooks would work as expected with python_poise.


I will branch out and try out some of the proposed fixes for issues noted above..

But before that, since this python cookbook is only part of a demo cookbook and a recipe in mu-tools (ebs-rolling-snapshots : which is not part of any roles run_lists on mu-master) do we continue to update these issues?

**Comment by agill17** [comment]
The mu-tools::ebs_rolling_snapshots upgrades 2 pip packages using python_pip resource (which should be able to update using poise_python's resources) and handles managing ebs volume snapshots using a python script

**Comment by agill17** [comment]
Resolved Here; [#83](https://github.com/cloudamatic/mu/pull/83)
